/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as SecondRouteImport } from './routes/second'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as ProgramsProgramIdIndexRouteImport } from './routes/programs.$programId.index'
import { Route as ProgramsProgramIdModulesModuleIdRouteImport } from './routes/programs.$programId.modules.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondRoute = SecondRouteImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdIndexRoute = ProgramsProgramIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsProgramIdRoute,
} as any)
const ProgramsProgramIdModulesModuleIdRoute =
  ProgramsProgramIdModulesModuleIdRouteImport.update({
    id: '/modules/$moduleId',
    path: '/modules/$moduleId',
    getParentRoute: () => ProgramsProgramIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/modules/$moduleId': typeof ProgramsProgramIdModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
  '/programs/$programId': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/modules/$moduleId': typeof ProgramsProgramIdModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/second': typeof SecondRoute
  '/settings': typeof SettingsRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/programs/$programId/': typeof ProgramsProgramIdIndexRoute
  '/programs/$programId/modules/$moduleId': typeof ProgramsProgramIdModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/second'
    | '/settings'
    | '/programs/$programId'
    | '/programs/$programId/'
    | '/programs/$programId/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/second'
    | '/settings'
    | '/programs/$programId'
    | '/programs/$programId/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/second'
    | '/settings'
    | '/programs/$programId'
    | '/programs/$programId/'
    | '/programs/$programId/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  SecondRoute: typeof SecondRoute
  SettingsRoute: typeof SettingsRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/': {
      id: '/programs/$programId/'
      path: '/'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof ProgramsProgramIdIndexRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
    '/programs/$programId/modules/$moduleId': {
      id: '/programs/$programId/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/programs/$programId/modules/$moduleId'
      preLoaderRoute: typeof ProgramsProgramIdModulesModuleIdRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
  }
}

interface ProgramsProgramIdRouteChildren {
  ProgramsProgramIdIndexRoute: typeof ProgramsProgramIdIndexRoute
  ProgramsProgramIdModulesModuleIdRoute: typeof ProgramsProgramIdModulesModuleIdRoute
}

const ProgramsProgramIdRouteChildren: ProgramsProgramIdRouteChildren = {
  ProgramsProgramIdIndexRoute: ProgramsProgramIdIndexRoute,
  ProgramsProgramIdModulesModuleIdRoute: ProgramsProgramIdModulesModuleIdRoute,
}

const ProgramsProgramIdRouteWithChildren =
  ProgramsProgramIdRoute._addFileChildren(ProgramsProgramIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  SecondRoute: SecondRoute,
  SettingsRoute: SettingsRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
